### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by Kenoshen** [Kenoshen/animagic#1]
The ui should allow you to:
- load up an animation
- mark key frames
- create a state machine to link animations together
- save an animation
- maybe create a single file that contains all the image data and animation data?

**Comment by MondayHopscotch** [comment]
As part of the UI (I love the idea of a UI to make rigging animations easier, btw), I was thinking it might be super useful to have a way to set an origin point on a per-frame basis (and it defaults to the same coordinate in each frame) so we can line up animations as we need. It would make dealing with the need of offsetting an animation to make things display correctly in-game.

**Comment by Kenoshen** [comment]
Duplicate of #17
